// Mirror of src/data/roles.ts's {title, slug} pairs, since Deno edge
// functions can't import from src/ (a separate Vite build). Regenerate this
// list whenever roles.ts changes - the sync-skills-england function keeps
// its own copy the same way, for the same reason.
export const ROLE_SLUGS: { title: string; slug: string }[] = [
  { title: "AI", slug: "ai" },
  { title: "Commercial", slug: "commercial" },
  { title: "Creative", slug: "creative" },
  { title: "E-commerce", slug: "ecommerce" },
  { title: "Finance / Accounting", slug: "finance" },
  { title: "IT & Technology", slug: "it-technology" },
  { title: "Legal & Compliance", slug: "legal-compliance" },
  { title: "Marketing", slug: "marketing" },
  { title: "Operations", slug: "operations" },
  { title: "People & Culture", slug: "hr-people" },
  { title: "Product", slug: "product" },
  { title: "Project & Programme Management", slug: "project-management" },
  { title: "Sales", slug: "sales" },
  { title: "Strategy", slug: "strategy" },
  { title: "Sustainability Manager", slug: "sustainability" },
  { title: "Barista", slug: "barista" },
  { title: "Bartender / Front of House", slug: "bartender" },
  { title: "Charity Fundraiser", slug: "charity-fundraiser" },
  { title: "Chef / Baker", slug: "chef" },
  { title: "Estate Agent", slug: "estate-agent" },
  { title: "Fitness Instructor", slug: "fitness-instructor" },
  { title: "Garment Technologist", slug: "garment-technologist" },
  { title: "Hotel Manager", slug: "hotel-manager" },
  { title: "Mortgage Advisor", slug: "mortgage-advisor" },
  { title: "Personal Trainer", slug: "personal-trainer" },
  { title: "Physiotherapist", slug: "physiotherapist" },
  { title: "Producer", slug: "producer" },
  { title: "Psychotherapist", slug: "psychotherapist" },
  { title: "Stylist / Designer", slug: "stylist" },
  { title: "Teacher", slug: "teacher" },
  { title: "Conveyancer", slug: "conveyancer" },
  { title: "Lettings Negotiator", slug: "lettings-negotiator" },
  { title: "Property Manager", slug: "property-manager" },
  { title: "Car Sales Executive", slug: "car-sales-executive" },
  { title: "Veterinary Surgeon", slug: "veterinary-surgeon" },
  { title: "Veterinary Nurse", slug: "veterinary-nurse" },
  { title: "Occupational Therapist", slug: "occupational-therapist" },
  { title: "Teaching Assistant", slug: "teaching-assistant" },
  { title: "Buyer / Merchandiser", slug: "buyer" },
  { title: "Data Analyst", slug: "data-analyst" },
  { title: "Customer Service", slug: "customer-service" },
  { title: "Beauty Therapist", slug: "beauty-therapist" },
  { title: "Farmer", slug: "farmer" },
  { title: "Retail Assistant", slug: "retail-assistant" },
  { title: "Vehicle Technician", slug: "vehicle-technician" },
  { title: "Warehouse & Delivery", slug: "warehouse-delivery" },
  { title: "Agronomist", slug: "agronomist" },
  { title: "Farm Manager", slug: "farm-manager" },
  { title: "Farm Worker", slug: "farm-worker" },
  { title: "Nurse", slug: "nurse" },
  { title: "Doctor / GP", slug: "doctor" },
  { title: "Healthcare Assistant", slug: "healthcare-assistant" },
  { title: "Midwife", slug: "midwife" },
  { title: "Care Worker", slug: "care-worker" },
  { title: "Jockey", slug: "jockey" },
  { title: "Racehorse Trainer", slug: "racehorse-trainer" },
  { title: "Stable Hand / Groom", slug: "stable-hand" },
  { title: "Financial Advisor", slug: "financial-advisor" },
  { title: "Wealth Manager", slug: "wealth-manager" },
  { title: "Investment Analyst", slug: "investment-analyst" },
  { title: "Mortgage Broker", slug: "mortgage-broker" },
  { title: "Race Engineer", slug: "race-engineer" },
  { title: "Mechanic", slug: "mechanic" },
  { title: "Aerodynamicist", slug: "aerodynamicist" },
  { title: "Performance Engineer", slug: "performance-engineer" },
  { title: "Composite Technician", slug: "composite-technician" },
  { title: "Football Coach", slug: "football-coach" },
  { title: "Scout", slug: "football-scout" },
  { title: "Sports Scientist", slug: "sports-scientist" },
  { title: "Physiotherapist (Football)", slug: "football-physio" },
  { title: "Groundsperson", slug: "groundsperson" },
  { title: "Kit Manager", slug: "kit-manager" },
  { title: "Performance Analyst (Football)", slug: "football-analyst" },
  { title: "Academy Coach", slug: "academy-coach" },
  { title: "Reporter / Journalist", slug: "reporter" },
  { title: "Editor", slug: "editor" },
  { title: "Broadcast Journalist", slug: "broadcast-journalist" },
  { title: "Game Designer", slug: "game-designer" },
  { title: "QA Tester", slug: "qa-tester" },
  { title: "Sound Engineer", slug: "sound-engineer" },
  { title: "Live Events / Tour Manager", slug: "live-events-manager" },
  { title: "Travel Agent / Consultant", slug: "travel-consultant" },
  { title: "Interior Designer", slug: "interior-designer" },
  { title: "Store Manager (Retail)", slug: "grocery-store-manager" },
  { title: "Policy Advisor", slug: "policy-advisor" },
  { title: "Parliamentary Researcher", slug: "parliamentary-researcher" },
  { title: "Council Officer", slug: "council-officer" },
  { title: "Think Tank Researcher", slug: "think-tank-researcher" },
  { title: "Public Affairs Manager", slug: "public-affairs-manager" },
  { title: "Performer", slug: "performer" },
  { title: "Stage Manager", slug: "theatre-stage-manager" },
  { title: "Theatre Technician", slug: "theatre-technician" },
  { title: "Costume & Design", slug: "theatre-costume-designer" },
  { title: "Theatre Producer", slug: "theatre-producer" },
  { title: "Electrician", slug: "electrician" },
  { title: "Plumber", slug: "plumber" },
  { title: "Heating & Gas Engineer", slug: "heating-engineer" },
  { title: "Repair Technician", slug: "repair-technician" },
  { title: "Handyperson / Multi-Trade", slug: "handyperson" },
  { title: "Bricklayer", slug: "bricklayer" },
  { title: "Carpenter / Joiner", slug: "carpenter" },
  { title: "Plasterer", slug: "plasterer" },
  { title: "Groundworker", slug: "groundworker" },
  { title: "Roofer", slug: "roofer" },
];

/**
 * Resolve a free-text role name (as a user or Howdy might type it) to a real
 * roles.ts slug. Exact case-insensitive title match first, then a loose
 * substring match as a fallback for close variants (e.g. "plumbers" ->
 * "Plumber"). Returns null rather than guessing when nothing confident.
 */
export function resolveRoleTitleToSlug(input: string): { slug: string; title: string } | null {
  const q = input.trim().toLowerCase();
  if (!q) return null;
  const exact = ROLE_SLUGS.find((r) => r.title.toLowerCase() === q);
  if (exact) return exact;
  const substring = ROLE_SLUGS.find((r) => r.title.toLowerCase().includes(q) || q.includes(r.title.toLowerCase()));
  return substring ?? null;
}
