// CoachPlanPanel — The Plan: Howdy's checklist for the user's active target
// role. Deterministic tasks are generated by useCoachPlan from data that
// already exists (skill gaps, CV, badges, courses); Howdy can also add its
// own bespoke tasks mid-conversation via the add_coach_task tool.

import { Link } from "react-router-dom";
import { CheckCircle2, Circle, ArrowRight, Star } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { useCoachPlan, type CoachPlanTask } from "@/hooks/useCoachPlan";

const TASK_ICON: Record<string, string> = {
  rate_skills: "⭐",
  upload_cv: "📄",
  build_experience: "🤝",
  take_course: "🎓",
  stand_out: "✨",
  custom: "💬",
};

function TaskRow({ task, onComplete, onReopen }: {
  task: CoachPlanTask;
  onComplete: (id: string) => void;
  onReopen: (id: string) => void;
}) {
  const isDone = task.status === "done";
  return (
    <div className={`flex items-start gap-3 py-3 border-b border-border/50 last:border-0 ${isDone ? "opacity-50" : ""}`}>
      <button
        onClick={() => (isDone ? onReopen(task.id) : onComplete(task.id))}
        className="shrink-0 mt-0.5"
        aria-label={isDone ? "Mark as not done" : "Mark as done"}
      >
        {isDone
          ? <CheckCircle2 className="w-5 h-5 text-primary" />
          : <Circle className="w-5 h-5 text-muted-foreground hover:text-primary transition-colors" />}
      </button>
      <div className="flex-1 min-w-0">
        <p className={`font-display font-700 text-sm leading-snug ${isDone ? "line-through" : ""}`}>
          <span className="mr-1.5">{TASK_ICON[task.task_type] ?? "•"}</span>
          {task.title}
        </p>
        {task.detail && (
          <p className="font-body text-xs text-muted-foreground mt-0.5">{task.detail}</p>
        )}
        {task.link && !isDone && (
          <Link
            to={task.link}
            className="inline-flex items-center gap-1 font-display font-700 text-xs text-primary hover:opacity-80 transition-opacity mt-1.5"
          >
            Go do it <ArrowRight className="w-3 h-3" />
          </Link>
        )}
        {task.source === "howdy" && (
          <span className="inline-block mt-1 text-[10px] font-display font-600 uppercase tracking-wide text-muted-foreground/70">
            Added by Howdy
          </span>
        )}
      </div>
    </div>
  );
}

export default function CoachPlanPanel({ compact = false }: { compact?: boolean }) {
  const { user } = useAuth();
  const {
    activeRoleTitle, readiness, ratedCount, totalCount, openTasks, doneTasks,
    loading, completeTask, reopenTask,
  } = useCoachPlan(user?.id);

  if (!user) return null;
  if (loading) return <div className="h-24 bg-muted/30 rounded-2xl animate-pulse" />;

  if (!activeRoleTitle) {
    return (
      <div className="border-2 border-dashed border-border rounded-2xl p-6 text-center">
        <p className="font-display font-700 text-sm mb-1">Set a target role to get your plan</p>
        <p className="font-body text-xs text-muted-foreground mb-3">
          Pick a role from any role page, or tell Howdy what you're aiming for.
        </p>
        <Link
          to="/roles"
          className="inline-flex items-center gap-1.5 font-display font-700 text-xs text-primary hover:opacity-80 transition-opacity"
        >
          Browse roles <ArrowRight className="w-3 h-3" />
        </Link>
      </div>
    );
  }

  const shownOpen = compact ? openTasks.slice(0, 3) : openTasks;

  return (
    <div className="border-2 border-foreground/10 bg-muted/20 rounded-2xl p-5">
      <div className="flex items-center justify-between gap-3 mb-1 flex-wrap">
        <p className="font-display font-700 text-xs uppercase tracking-widest text-muted-foreground">
          Your Plan · {activeRoleTitle}
        </p>
        {totalCount > 0 && (
          <span className={`font-display font-900 text-sm ${readiness >= 70 ? "text-green-600" : readiness >= 40 ? "text-amber-600" : "text-red-500"}`}>
            {readiness}% ready
          </span>
        )}
      </div>
      {totalCount > 0 && (
        <p className="font-body text-xs text-muted-foreground mb-4">
          {ratedCount}/{totalCount} skills rated
        </p>
      )}

      {shownOpen.length === 0 && doneTasks.length > 0 && (
        <p className="font-body text-sm text-muted-foreground flex items-center gap-1.5 py-3">
          <Star className="w-4 h-4 fill-current text-primary" /> Nothing outstanding right now - nice work.
        </p>
      )}

      <div>
        {shownOpen.map((t) => (
          <TaskRow key={t.id} task={t} onComplete={completeTask} onReopen={reopenTask} />
        ))}
      </div>

      {compact && openTasks.length > 3 && (
        <Link
          to="/skills-passport"
          className="inline-flex items-center gap-1 font-display font-700 text-xs text-primary hover:opacity-80 transition-opacity mt-2"
        >
          See all {openTasks.length} tasks <ArrowRight className="w-3 h-3" />
        </Link>
      )}

      {!compact && doneTasks.length > 0 && (
        <details className="mt-4">
          <summary className="font-display font-700 text-xs text-muted-foreground cursor-pointer hover:text-foreground">
            {doneTasks.length} completed
          </summary>
          <div className="mt-2">
            {doneTasks.map((t) => (
              <TaskRow key={t.id} task={t} onComplete={completeTask} onReopen={reopenTask} />
            ))}
          </div>
        </details>
      )}
    </div>
  );
}
