// CoachPlanPanel — The Plan: Howdy's checklist for each of the user's target
// roles. Deterministic tasks are generated by useCoachPlan from data that
// already exists (skill gaps, CV, badges, courses); Howdy can also add its
// own bespoke tasks mid-conversation via the add_coach_task tool.

import { useState } from "react";
import { Link } from "react-router-dom";
import { CheckCircle2, Circle, ArrowRight, Star } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { useCoachPlan, type CoachPlanTask, type RolePlan } from "@/hooks/useCoachPlan";
import { useTargetRoles } from "@/hooks/useTargetRoles";
import RoleSelector from "@/components/RoleSelector";

const TASK_ICON: Record<string, string> = {
  rate_skills: "⭐",
  upload_cv: "📄",
  build_experience: "🤝",
  take_course: "🎓",
  log_qualifications: "📜",
  external_qualification: "🌐",
  apply_now: "🚀",
  stand_out: "✨",
  custom: "💬",
};

function TaskRow({ task, roleLabel, onComplete, onReopen }: {
  task: CoachPlanTask;
  roleLabel?: string;
  onComplete: (id: string) => void;
  onReopen: (id: string) => void;
}) {
  const isDone = task.status === "done";
  return (
    <div className={`flex items-start gap-3 py-3 border-b border-border/50 last:border-0 ${isDone ? "opacity-50" : ""}`}>
      <button
        onClick={() => (isDone ? onReopen(task.id) : onComplete(task.id))}
        className="shrink-0 mt-0.5"
        aria-label={isDone ? "Mark as not done" : "Mark as done"}
      >
        {isDone
          ? <CheckCircle2 className="w-5 h-5 text-primary" />
          : <Circle className="w-5 h-5 text-muted-foreground hover:text-primary transition-colors" />}
      </button>
      <div className="flex-1 min-w-0">
        <p className={`font-display font-700 text-sm leading-snug ${isDone ? "line-through" : ""}`}>
          <span className="mr-1.5">{TASK_ICON[task.task_type] ?? "•"}</span>
          {task.title}
          {roleLabel && (
            <span className="ml-2 text-[10px] font-display font-600 uppercase tracking-wide text-primary/70">
              {roleLabel}
            </span>
          )}
        </p>
        {task.detail && (
          <p className="font-body text-xs text-muted-foreground mt-0.5">{task.detail}</p>
        )}
        {task.link && !isDone && (
          <Link
            to={task.link}
            className="inline-flex items-center gap-1 font-display font-700 text-xs text-primary hover:opacity-80 transition-opacity mt-1.5"
          >
            Go do it <ArrowRight className="w-3 h-3" />
          </Link>
        )}
        {task.source === "howdy" && (
          <span className="inline-block mt-1 text-[10px] font-display font-600 uppercase tracking-wide text-muted-foreground/70">
            Added by Howdy
          </span>
        )}
      </div>
    </div>
  );
}

function RolePlanCard({ plan, onComplete, onReopen }: {
  plan: RolePlan;
  onComplete: (id: string) => void;
  onReopen: (id: string) => void;
}) {
  return (
    <div className="border-2 border-foreground/10 bg-muted/20 rounded-2xl p-5 mb-4 last:mb-0">
      <div className="flex items-center justify-between gap-3 mb-1 flex-wrap">
        <p className="font-display font-700 text-xs uppercase tracking-widest text-muted-foreground">
          Your Plan ·{" "}
          <Link
            to={`/skills-passport?tab=assessment&role=${plan.role_slug}`}
            className="text-primary hover:underline"
          >
            {plan.role_title}
          </Link>
        </p>
        {plan.totalCount > 0 && (
          <span className={`font-display font-900 text-sm ${plan.readiness >= 70 ? "text-green-600" : plan.readiness >= 40 ? "text-amber-600" : "text-red-500"}`}>
            {plan.readiness}% ready
          </span>
        )}
      </div>
      {plan.totalCount > 0 && (
        <p className="font-body text-xs text-muted-foreground mb-4">
          {plan.ratedCount}/{plan.totalCount} skills rated
        </p>
      )}

      {plan.openTasks.length === 0 && plan.doneTasks.length > 0 && (
        <p className="font-body text-sm text-muted-foreground flex items-center gap-1.5 py-3">
          <Star className="w-4 h-4 fill-current text-primary" /> Nothing outstanding right now - nice work.
        </p>
      )}

      <div>
        {plan.openTasks.map((t) => (
          <TaskRow key={t.id} task={t} onComplete={onComplete} onReopen={onReopen} />
        ))}
      </div>

      {plan.doneTasks.length > 0 && (
        <details className="mt-4">
          <summary className="font-display font-700 text-xs text-muted-foreground cursor-pointer hover:text-foreground">
            {plan.doneTasks.length} completed
          </summary>
          <div className="mt-2">
            {plan.doneTasks.map((t) => (
              <TaskRow key={t.id} task={t} onComplete={onComplete} onReopen={onReopen} />
            ))}
          </div>
        </details>
      )}
    </div>
  );
}

export default function CoachPlanPanel({ compact = false }: { compact?: boolean }) {
  const { user } = useAuth();
  const { rolePlans, loading, completeTask, reopenTask } = useCoachPlan(user?.id);
  const { addTargetRole } = useTargetRoles(user?.id);
  const [pickedRole, setPickedRole] = useState("");
  const [settingRole, setSettingRole] = useState(false);

  if (!user) return null;
  if (loading) return <div className="h-24 bg-muted/30 rounded-2xl animate-pulse" />;

  if (rolePlans.length === 0) {
    const handleSetTargetRole = async () => {
      if (!pickedRole) return;
      setSettingRole(true);
      await addTargetRole(pickedRole);
      setSettingRole(false);
    };

    if (compact) {
      return (
        <div className="border-2 border-dashed border-border rounded-2xl p-6 text-center">
          <p className="font-display font-700 text-sm mb-1">Set a target role to get your plan</p>
          <p className="font-body text-xs text-muted-foreground mb-3">
            Pick a role from any role page, or tell Howdy what you're aiming for.
          </p>
          <Link
            to="/roles"
            className="inline-flex items-center gap-1.5 font-display font-700 text-xs text-primary hover:opacity-80 transition-opacity"
          >
            Browse roles <ArrowRight className="w-3 h-3" />
          </Link>
        </div>
      );
    }

    return (
      <div className="border-2 border-dashed border-border rounded-2xl p-6 text-center">
        <p className="font-display font-700 text-sm mb-1">Set a target role to get your plan</p>
        <p className="font-body text-xs text-muted-foreground mb-4">
          Pick the role you're aiming for below and Howdy builds your checklist from it - skill gaps, badges, courses, the lot.
        </p>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-2">
          <RoleSelector selected={pickedRole} onChange={(slug) => setPickedRole(slug)} className="w-full sm:w-72" />
          <button
            onClick={handleSetTargetRole}
            disabled={!pickedRole || settingRole}
            className="w-full sm:w-auto shrink-0 px-4 py-2.5 font-display font-700 text-sm bg-primary text-primary-foreground rounded-xl hover:opacity-90 transition-opacity disabled:opacity-50"
          >
            {settingRole ? "Setting…" : "Set as target role"}
          </button>
        </div>
        <Link
          to="/roles"
          className="inline-flex items-center gap-1.5 font-display font-700 text-xs text-primary hover:opacity-80 transition-opacity mt-4"
        >
          Or browse roles <ArrowRight className="w-3 h-3" />
        </Link>
      </div>
    );
  }

  if (!compact) {
    return (
      <div>
        {rolePlans.map((plan) => (
          <RolePlanCard key={plan.role_slug} plan={plan} onComplete={completeTask} onReopen={reopenTask} />
        ))}
      </div>
    );
  }

  // Compact (chat-widget strip): a condensed cross-role summary rather than
  // one full card per role, so it doesn't balloon with 3+ active roles.
  const allOpen = rolePlans.flatMap((p) => p.openTasks.map((t) => ({ task: t, roleLabel: p.role_title })));
  const shown = allOpen.slice(0, 3);

  return (
    <div className="border-2 border-foreground/10 bg-muted/20 rounded-2xl p-5">
      <div className="flex items-center justify-between gap-3 mb-1 flex-wrap">
        <p className="font-display font-700 text-xs uppercase tracking-widest text-muted-foreground">
          Your Plan · {rolePlans.length} role{rolePlans.length !== 1 ? "s" : ""}
        </p>
      </div>
      <div className="flex flex-wrap gap-x-3 gap-y-1 mb-3">
        {rolePlans.map((p) => (
          <span key={p.role_slug} className={`font-display font-700 text-xs ${p.readiness >= 70 ? "text-green-600" : p.readiness >= 40 ? "text-amber-600" : "text-red-500"}`}>
            {p.role_title} {p.readiness}%
          </span>
        ))}
      </div>

      {shown.length === 0 ? (
        <p className="font-body text-sm text-muted-foreground flex items-center gap-1.5 py-3">
          <Star className="w-4 h-4 fill-current text-primary" /> Nothing outstanding right now - nice work.
        </p>
      ) : (
        <div>
          {shown.map(({ task, roleLabel }) => (
            <TaskRow
              key={task.id}
              task={task}
              roleLabel={rolePlans.length > 1 ? roleLabel : undefined}
              onComplete={completeTask}
              onReopen={reopenTask}
            />
          ))}
        </div>
      )}

      {allOpen.length > 3 && (
        <Link
          to="/skills-passport"
          className="inline-flex items-center gap-1 font-display font-700 text-xs text-primary hover:opacity-80 transition-opacity mt-2"
        >
          See all {allOpen.length} tasks <ArrowRight className="w-3 h-3" />
        </Link>
      )}
    </div>
  );
}
