// Auto-curated YouTube "day in the life" videos per role.
// Generated by scripts/role-youtube-fetch.py from YouTube search.
// Re-run that script to refresh.

export interface RoleYouTubeVideo {
  id: string;
  title: string;
  channel: string;
}

export const ROLE_YOUTUBE_VIDEOS: Record<string, RoleYouTubeVideo[]> = {
  "academy-coach": [
    { id: "OUZH0zUCTyc", title: "Day in the Life | Forest Academy Hybrid Player ð¬", channel: "Nottingham Forest FC " },
    { id: "5mdSkENlcR0", title: "Burnley Academy: A Day in the Life | FEATURES", channel: "Burnley Football Club" },
    { id: "Nx1f5VsLPSg", title: "A Day in The Life of a Rangers Academy Player | Oliver Hynd", channel: "Rangers Football Club (Official)" },
    { id: "JXMFfqOq3KU", title: "Inside Our Academy ð« | Exclusive Look At Our Future Generations", channel: "Leicester City" },
  ],
  "aerodynamicist": [
    { id: "yQmHhtAIw_g", title: "My Job in F1: Ola | Aerodynamics", channel: "Mercedes-AMG Petronas Formula One Team" },
    { id: "B19W8XQ8Ebc", title: "So, you want to be an F1 Aerodynamicist?", channel: "Aston Martin Aramco Formula Oneâ¢ Team" },
    { id: "YLob1yARX7M", title: "How Elon Musk Learned Aerospace Engineering without a degree?", channel: "LIFETIME advice" },
    { id: "Ju5nmWPbM68", title: "DAY IN THE LIFE OF A MECHANICAL ENGINEER! (AEROSPACE EDITION)", channel: "Wissam Seif" },
  ],
  "agronomist": [
    { id: "KRcGjRZT5UY", title: "RCAA Careers -  Agronomy", channel: "Royal Cornwall Show" },
    { id: "QJBhDYKewk4", title: "David Barclay- Agronomist", channel: "SAYFC" },
    { id: "9WCqEa39KDY", title: "What does an agronomist do?", channel: "eatfarmnow" },
    { id: "YYx7MGlAYjk", title: "Meet the Farmers: Agronomist", channel: "James Dyson Foundation" },
  ],
  "ai": [
    { id: "vBn5aZOJJzo", title: "Day in Life as an AI Engineer - Coding Vlog", channel: "Nicolai Nielsen" },
    { id: "4kXecGkdw4E", title: "Day in the Life of an AI Engineer", channel: "Springboard" },
    { id: "tXG1PfAM0kE", title: "Day in the Life of an AI Research Engineer in NYC", channel: "Code Monki" },
    { id: "3JP_RVq3Ngk", title: "A Day in the Life of an AI Researcher at Facebook (AI Resident)", channel: "Oleksii Sidorov" },
  ],
  "barista": [
    { id: "GZK3luefIoQ", title: "Day In The Life Of A Barista: from start to close full day vlog", channel: "Ryan Dean Dexton" },
    { id: "-uCfiSg9XC8", title: "What does BARISTA ACTUALLY do at work? A day in the life of a barista!", channel: "European Coffee Trip" },
    { id: "ToSvksDiUi0", title: "A day in my life as a barista: from opening to closing | åå¡å¸çä¸å¤© | London Vlog #11", channel: "Jessie Gao æ°è¥¿" },
    { id: "rcTUvKYCEJo", title: "A Day in the Life of a Barista âï¸ | Indeed", channel: "Indeed" },
  ],
  "bartender": [
    { id: "9D9h53Q1AEA", title: "POV: Bartender at a Top London Restaurant", channel: "Fallow" },
    { id: "nPltnMj5Gao", title: "So You Want To Be A Bartender", channel: "Nelson Lam" },
    { id: "O3hOKkc8fBk", title: "4. How to make Pub drinks", channel: "UEAUnionBars" },
    { id: "INsTqoff0F4", title: "5. Things not to do behind the bar...", channel: "UEAUnionBars" },
  ],
  "beauty-therapist": [
    { id: "VZjmcCm9aBo", title: "DAY in the life of a SOLO ESTHETICIAN: fully booked day, room + facial cart setup", channel: "Julie Ruby" },
    { id: "BKBIUl4t_zo", title: "day in the life of a beauty therapist: electrolysis hair removal & nails", channel: "Melis Ates" },
    { id: "7fU6fU5tvjc", title: "Vlogging my full work day as a successful home Beauty Therapist â¨ï¸", channel: "Huyana Beauty" },
    { id: "px2qGQEtSNI", title: "HOW TO BECOME AN AESTHETICIAN IN UK | AESTHETICIAN SCHOOLS IN UK | BEAUTY THERAPIST", channel: "Oluchi Onuigbo" },
  ],
  "bricklayer": [
    { id: "JUFJYLNMKNI", title: "Working with an Apprentice Bricklayer", channel: "Charlie Collison" },
  ],
  "broadcast-journalist": [
    { id: "XfzGKRIBTuk", title: "BEHIND THE SCENES | A Day In The Life Of A Liverpool Reporter", channel: "David Lynch - Liverpool FC" },
    { id: "jEWq1Y6q8Bg", title: "A day in the life of a Broadcast Journalism student at Nottingham Trent University", channel: "Nottingham Trent University" },
    { id: "Dbe8kVB9YWE", title: "Day in the life of a MA Broadcast Journalism student | University of Sheffield", channel: "The University of Sheffield" },
    { id: "-hX-BVcx7WA", title: "HotTakes: A Day in the Life of a Broadcast Journalist", channel: "Hotwire Global Communications" },
  ],
  "buyer": [
    { id: "Lz7u-ty19yY", title: "Day In The Life Of A Trainee Buyer At NEXT", channel: "Life at Next" },
    { id: "L4BnpZquw5o", title: "What does a Fashion Buyer ACTUALLY do?! How to become a Fashion Buyer for beginners", channel: "Emma Jayne" },
    { id: "FvZEToYw8Oo", title: "Day In The Life Of A Trainee Merchandiser", channel: "Life at Next" },
    { id: "ee1ivQk_v4I", title: "Life As A Fashion Buyer | Breaking Fashion", channel: "BBC Three" },
  ],
  "car-sales-executive": [
    { id: "e_4_HBThuwE", title: "A Day in the Life of a Car Salesperson | ep1", channel: "Jacob Sotiris - Video Marketing Coach" },
    { id: "33_f4hYjTME", title: "Day in the life as a car salesman (a real day)", channel: "Joshua Stonum" },
    { id: "LMgwDOiiYzk", title: "Day in the Life of a Car Salesman: Saturday Edition | Car Salesman Tips and VLOG", channel: "Cars Unlocked" },
    { id: "t8eDALRZdsM", title: "EP 1: A Day in the Life of a Car Dealership", channel: "Motor4u" },
  ],
  "care-worker": [
    { id: "lTv53IhSwKk", title: "Day in the Life of Home Care", channel: "ScottishCare" },
    { id: "EHGixZ_cEoE", title: "A day in the life of a support worker at Broughton Lodge, Cygnet Health Care", channel: "Life Changing Careers by Cygnet" },
    { id: "HE8L6dr1sXE", title: "Day in the life - Healthcare support worker", channel: "University Hospitals Bristol and Weston NHS FT" },
    { id: "Ag_DNm-jJzM", title: "Day In the Life of A Support Worker", channel: "Rehability UK" },
  ],
  "carpenter": [
    { id: "_thN9c_6mPc", title: "Day in the life of a carpentry apprentice | should you become an apprentice in 2025", channel: "Official_apprentice" },
  ],
  "charity-fundraiser": [
    { id: "F2BAKWihXqA", title: "A day in the life - Vikki our Events and Individual Challenge Fundraiser", channel: "Dove House Hospice" },
    { id: "FPPjc0nmE4Q", title: "Community Fundraising | A Day in the Life | Newlife the Charity for Disabled Children", channel: "Newlife the Charity for Disabled Children" },
    { id: "OVXeiI97HMg", title: "Fundraiser's advice to new starters", channel: "Charity Link" },
    { id: "AYKfdscj5Fs", title: "Fundraising Manager - Career Insights (Careers in Charity)", channel: "Career Insights" },
  ],
  "chef": [
    { id: "CX30nlWGeeU", title: "Bakery life- 24hrs in my little bakery", channel: "kittytaitbaker" },
    { id: "5e_49V2poA0", title: "A Day In The Life Of A BAKER | LONDON", channel: "Kris Kazlauskaite" },
    { id: "_qEAiRtbWfU", title: "5 AM BAKING shift | A day in the life of A BAKER", channel: "Kris Kazlauskaite" },
    { id: "djmhynTcZv8", title: "A Day in the Life of a Baker | Indeed", channel: "Indeed" },
  ],
  "commercial": [
    { id: "P-gLMY9raMg", title: "A day in the life of an ABP Commercial Apprentice", channel: "Associated British Ports" },
    { id: "FDUlqwwnGeE", title: "Day in the Life - Commercial & Marketing Graduate", channel: "VodafoneThree UK Life" },
  ],
  "composite-technician": [
    { id: "BO97VDDmtPc", title: "Our jobs #01 Laura composite technician - English subtitles", channel: "Groupe Beneteau" },
    { id: "ekEFVpm6fhA", title: "Meet Caleb, a proud 3rd year composites technician here at Riviera", channel: "Riviera Australia" },
    { id: "h1jTsDGqGLg", title: "CAD Technician - Day in the Life", channel: "TTLInc" },
    { id: "8O9FCMlOl7s", title: "A Day in the Life of an Assembler: Meet Cameron", channel: "Rockwell Automation" },
  ],
  "conveyancer": [
    { id: "8c5V0--G0pg", title: "A Day in the Life of a Conveyancer", channel: "Harding Evans Solicitors" },
    { id: "657g5DdjNnE", title: "Jocelyn Lucas Interview - Role of a Conveyancer", channel: "Loan Studio" },
    { id: "ieofu2iw2bY", title: "A day in the life of a Paralegal in the UK", channel: "Media with ibs" },
    { id: "MKWFLXnFe-k", title: "A Day in the life of a Trainee Solicitor in London | Real Estate | Lawyer Life", channel: "Simranjeet Kaur Mann" },
  ],
  "creative": [
    { id: "0y1aNGfj1is", title: "A Day in the Life | What Instructional Designers REALLY Do", channel: "Devlin Peck" },
    { id: "bK_fnLCgF9M", title: "How to Become a Creative Director with Alexa Chung | Future of Fashion | British Vogue", channel: "Vogue" },
    { id: "wqM1zvfKfXE", title: "my quiet creative life in london", channel: "lexie " },
    { id: "e-HZ2TIVULI", title: "A Day in the Life of Fashion Designer Thom Browne | Vogue", channel: "Vogue" },
  ],
  "customer-service": [
    { id: "aeWGQqp-M70", title: "A Day in the life of a Customer Service Representative", channel: "Farmers Insurance" },
    { id: "uXV-aOs2_oo", title: "A Day in the life of an Office Claims Representative", channel: "Farmers Insurance" },
    { id: "bfvuRcWwxD4", title: "A day in the life of an Insurance Broker in the UK", channel: "Gary Das" },
    { id: "Eq7Z2i7m57Y", title: "6 Tips For Improving Your Customer Service Skills | Indeed Career Tips", channel: "Indeed" },
  ],
  "data-analyst": [
    { id: "XVY2XbNlqbA", title: "Day in the Life of a Data Analyst | UK (Remote)", channel: "Anas Riad" },
    { id: "8_6NNdtnUdw", title: "Life as a Data Analyst (tech) | My Corporate London Work Week", channel: "Ingrid Emilia" },
    { id: "JWczuteySBM", title: "Day in the Life of a Data Analyst: Meetings, SQL, So Much Food", channel: "Alex The Analyst" },
    { id: "izplYQJfepI", title: "Day in the Life of a Data Analyst Working in London", channel: "Junaid Ahmed" },
  ],
  "doctor": [
    { id: "lNXGfiO9dTM", title: "We are the NHS - A day in the life of a GP", channel: "NHS England " },
    { id: "e41JtZTvl8c", title: "Day In A Life Of A Doctor | GP Trainee in London", channel: "Dr Katherine Leung" },
    { id: "0GTj7C1yba0", title: "Day In The Life Of A Doctor | GP (General Practitioner)", channel: "Noyan Muini" },
    { id: "b7XAadLx4Fg", title: "DAY IN THE LIFE OF A DOCTOR | GP/ General Practice", channel: "Dr Punam Krishan" },
  ],
  "ecommerce": [
    
    { id: "CtC48m4D5nU", title: "A Day in the Life of an E-commerce Director/Manager", channel: "Alexander Skibinskiy" },
    { id: "NKd0EaQEQTY", title: "I Spent 6 Months Building This E-Commerce Business", channel: "3.7Million" },
    { id: "lAOw3MzRJJc", title: "Day In The Life of a Dropshipping Millionaire", channel: "Mackenzie Haldane" },
  ],
  "editor": [
    { id: "sWeMjVkhhQE", title: "What does a book editor do?", channel: "Penguin Random House UK" },
    { id: "bK_fnLCgF9M", title: "How to Become a Creative Director with Alexa Chung | Future of Fashion | British Vogue", channel: "Vogue" },
    { id: "-v4gHA8uYnk", title: "A Day With Eva Chen: CondÃ© Nast's Youngest Editor-In-Chief | Forbes", channel: "ForbesWomen" },
    { id: "WPJxoZevpYU", title: "FREELANCE YOUTUBE EDITING ð§â¨ | Realistic Day in My Life + How to Get Started! (Tips & Tricks)", channel: "Beth Gould" },
  ],
  "electrician": [
    { id: "yhRRRR2Tsx8", title: "Day in the life of an electrician - How much electricians earn in a day.", channel: "OM Electrical" },
    { id: "lifunadBZ3U", title: "A Day in the Life of an Electrician | Indeed", channel: "Indeed" },
  ],
  "estate-agent": [
    { id: "0tvv74Ek--E", title: "CHAOTIC Day in the life of an Estate Agent | one year later", channel: "Christina Williams" },
    { id: "bxhTGSAca2Y", title: "VLOG | A Work Week in My Life ð  As an estate agent", channel: "Alisha Franklin" },
    { id: "lsnACY-EqCM", title: "A day in the life of our estate agents in the Bedford office", channel: "Michael Graham Living" },
    { id: "SrGz4NbPgto", title: "Day In The Life Of An 18 Year Old Real Estate Agent | London UK", channel: "Bart Chmielecki" },
  ],
  "farm-manager": [
    { id: "bSLi2boNRsg", title: "A Day in the Life: Richard Primrose, Agri-Business Manager Bank of Ireland UK", channel: "OpenFarmWeekend" },
    { id: "7LJr8BO-5l8", title: "See my work as Assistant Farm Manager", channel: "Felix Thornley Cobbold Agricultural Trust" },
    { id: "vhDiNJ3_vhg", title: "Careers in Agriculture: Farm Manager - Ellie Norris", channel: "Oregon Agriculture in the Classroom" },
    { id: "WzpJzkjiaIc", title: "A Day in the Life of a Farm Manager- Come to work with me! (a fall day on the farm)", channel: "Erin Elyse" },
  ],
  "farm-worker": [
    { id: "CPfbwp9PUb0", title: "24 hours as an English Farmer", channel: "The School of Life" },
    { id: "wyzkpCdNRjc", title: "A DAY IN THE LIFE OF A FARMER #FARM24", channel: "Tom Pemberton Farm Life" },
    { id: "4LNtssf0KOw", title: "Day In My LIFE As 16-year-old FARMER |During Winter Months...", channel: "AG Farm Life" },
    { id: "-BFNEKQTgW0", title: "On the farm - a day in the life of an Arla dairy farmer", channel: "Arla UK" },
  ],
  "farmer": [
    { id: "3Ouk73Wlgos", title: "A DAY IN THE LIFE OF A FARMER... TWISTED COW, GIANT TRACTOR BLOW UP'S AND A MORNING OF FUN!", channel: "Tom Pemberton Farm Life" },
    { id: "CPfbwp9PUb0", title: "24 hours as an English Farmer", channel: "The School of Life" },
    { id: "KtYmwReypCs", title: "A Day In The Life Of British Farmers - The Unseen Reality! ", channel: "Sam Shutt Farming" },
    { id: "4LNtssf0KOw", title: "Day In My LIFE As 16-year-old FARMER |During Winter Months...", channel: "AG Farm Life" },
  ],
  "finance": [
    { id: "RiHzExK88II", title: "Day in the life of an Investment Banker in London", channel: "Haaris Zamir, CFA" },
    { id: "0s7HdgvSgf0", title: "Working in London as a qualified accountant - UK Vlog", channel: "Poppy Dontree" },
    { id: "bfvuRcWwxD4", title: "A day in the life of an Insurance Broker in the UK", channel: "Gary Das" },
    { id: "wqGErrMFI3A", title: "Working in Retail Banking: What it's like and my experience", channel: "Annie K" },
    { id: "1nF7m3HIGQY", title: "A Day in the Life of a Chartered Management Accountant", channel: "CRAIGO" },
    { id: "6RHsmXWFCFk", title: "A Day In My Life As An Investment Banker (The Honest Truth)", channel: "Nischa" },
  ],
  "financial-advisor": [
    { id: "Izo0jONlIXA", title: "A Day in the Life  - Financial Adviser in London (what really happens)", channel: "Principles Personal Finance" },
    { id: "xyCykKeYn7w", title: "What a Day in the Life of a UK Financial Adviser Really Looks Like", channel: "PaddyDenning" },
    { id: "7SlQuS7AOgQ", title: "Day in the Life of a Financial Advisor â Jamie Mannarelli", channel: "Northwestern Mutual" },
    { id: "iElfNR_0kkI", title: "Day in The Life of a Financial Advisor in 2022", channel: "Josh Olfert, CFP" },
  ],
  "fitness-instructor": [
    { id: "SlXeQanvZ1U", title: "A Day In A Life Of Fitness Instructor | Cycle Workshop in London | VLOG", channel: "Monika Chmielewska" },
    { id: "A6jbsrgX9J8", title: "DAY IN THE LIFE | pilates instructor, bo + tee haul, mat class, waitrose shop with me & more vlog uk", channel: "Georgie Clarke" },
    { id: "WevEd5z5aFM", title: "DAY IN MY LIFE AS A BARRE INSTRUCTOR ð©°â¨ teaching 3 classes, pilates certification, what's in my bag", channel: "Zoe Pritchard" },
    { id: "rT1JdMMCquE", title: "Parkwood Leisure & Life Fitness UK", channel: "Life Fitness / Hammer Strength" },
  ],
  "football-analyst": [
    { id: "F0V8vAkY3L4", title: "Scott Munro - Performance Analyst - A Day In The Life - Ep 2", channel: "Havant & Waterlooville Football Club" },
    { id: "vgO9o9Td6sI", title: "THE BACKROOM | SAM TUOHY, FOOTBALL ANALYST", channel: "QPR FC" },
    { id: "wgLRraJqsxM", title: "HIGH PERFORMANCE | THE TEAM BEHIND THE TEAM", channel: "Nottingham Forest FC " },
    { id: "4y5jSjsySlA", title: "Performance Analysis: Students of Portsmouth Football Club", channel: "University of Portsmouth" },
  ],
  "football-coach": [
    { id: "M8k1G8wuuMI", title: "A Day In The Life Of West Ham Manager Nuno EspÃ­rito Santo", channel: "Premier League and West Ham United FC" },
    { id: "Hd2pbHY5Xw8", title: "A Day in the Life of an Assistant Manager | Ben Petty, Birmingham City ð½ï¸", channel: "Birmingham City Football Club" },
    { id: "QP9NWNWE_vY", title: "A Day in the life of a UK Soccer Coach", channel: "UK International Soccer" },
    { id: "ndwBfyhLQxE", title: "Day in the Life of a Soccer Coach (Football Gaffer)", channel: "Matt Poland" },
  ],
  "football-physio": [
    { id: "lTWoOfIsP_U", title: "Ipswich Town's Alice Grindrod's day in the life as a sports therapist | On Her Turf | NBC Sports", channel: "NBC Sports" },
    { id: "HmpUOw19204", title: "Physio MIC'D UP! ð | Unique Matchday Insight | Inside Access", channel: "Watford FC" },
    { id: "RnHsG2UV4uU", title: "A Day in the Life of a Physiotherapist UK", channel: "Days of Dan" },
    { id: "acU16gEIl08", title: "Jake Travis - Head of Sports Therapy - A Day In The Life Ep 1", channel: "Havant & Waterlooville Football Club" },
  ],
  "football-scout": [
    { id: "Iiaaypkey9c", title: "Can Crystal Palace Coaches Foresee A Future Premier League Star? | Football Dreams: The Academy", channel: "Channel 4 Sport" },
    { id: "JkDkqHR3Nx8", title: "Day in the life of a European Football Scout", channel: "FOOTBALL SCOUTING WORLDWIDE" },
    { id: "CeW4dkgEcOc", title: "A message from our founder, Robert Baden-Powell to the young people | Scouting Heritage", channel: "World Scouting" },
    { id: "Z9JD0X2Cd_A", title: "A Day In The Life of an A&R Support Scout", channel: "Greater Music Group" },
  ],
  "game-designer": [
    { id: "vpSLpZc6TnU", title: "A Realistic Day in the Life of a FULL TIME Game Developer!", channel: "Game Dev Garnet" },
    { id: "ZEoyoXUoIX8", title: "What does a Game Designer REALLY do?", channel: "CG Spectrum" },
    { id: "RS9ec8SV77w", title: "A day in the life as a professional video game designer!", channel: "Games And Design" },
    { id: "VyabBp-QbqE", title: "I asked 100 gamedevs if a degree is worth it", channel: "BiteMe Games" },
  ],
  "garment-technologist": [
    { id: "NGPTHG0LDtQ", title: "Day In The Life Of A Garment Technologist at NEXT", channel: "Life at Next" },
    { id: "RxbA9PBy_I8", title: "Day In The Life Of A Garment Technologist", channel: "Life at Next" },
    { id: "HIcfkg_soSU", title: "Behind the Seams - A day in the life of a garment tech at out fashion factory", channel: "Fashion Capital" },
    { id: "v7iArv8GX9k", title: "My Journey Into Garment Technology", channel: "Designer Dorrys" },
  ],
  "grocery-store-manager": [
    { id: "URRU8L1l_EU", title: "Day in the life of a Store Manager | Coles Group", channel: "Life at Coles " },
    { id: "E2HPpZdFCFY", title: "The Truth About Working At Aldi, According To Employees", channel: "Mashed" },
    { id: "Jxb3iUwmr9o", title: "Working at Aldi - A day in the life of a shift manager", channel: "Pina's Life" },
    { id: "SWE19btev24", title: "Spend A Day As A Manager In One Of The Biggest NEXT Retail Stores!", channel: "Life at Next" },
  ],
  "groundsperson": [
    { id: "ZzfmUI9s0ps", title: "A Day in the Life of an Arborist I Russell Tree Experts", channel: "Russell Tree Experts" },
    { id: "_ApN9jpCOUc", title: "Arborists, 3 Quick Tips For Groundspeople aka (Groundies)", channel: "Arbor Now" },
    { id: "PMsNTk_ToLg", title: "A Day in the Life  - Groundman", channel: "Wright Tree Service" },
    { id: "9pU2GKwXiv8", title: "Groundsman Work During A Removal", channel: "All Natural Tree Experts" },
  ],
  "handyperson": [
    { id: "dGDzvIA_NrY", title: "Why I Charge £320 per day as a Handyman in 2024", channel: "Tradesman Tech Guy" },
  ],
  "healthcare-assistant": [
    { id: "HE8L6dr1sXE", title: "Day in the life - Healthcare support worker", channel: "University Hospitals Bristol and Weston NHS FT" },
    { id: "C2CFBva8rMk", title: "A Day in the Life of a Health Care Assistant (HCSW)", channel: "Gloucestershire Hospitals NHS Foundation Trust" },
    { id: "KB37boKaA1Y", title: "The life of a HCA", channel: "UHD NHS" },
    { id: "BsKoG8jabQ4", title: "A career in the NHS as a healthcare assistant", channel: "NHS Health Careers" },
  ],
  "heating-engineer": [
    { id: "mnOwbBDCNMk", title: "Boiler Repairs - Worcester, Vaillant, Glowworm + more | Day In The Life Of A Gas Engineer #13", channel: "Advanced Boiler Training" },
  ],
  "hotel-manager": [
    { id: "drGjMxKzYak", title: "A day in the life of a Travelodge Hotel Manager", channel: "TravelodgeUK" },
    { id: "ZgXdfRGU-tg", title: "Life of a Hotel Worker", channel: "Low Budget Stories" },
    { id: "q5E5olnNP_E", title: "A Day in the Life: Night Manager at a Luxury Hotel in Sydney | Is this for you?", channel: "Motion Artz" },
    { id: "Rd3DOhCKi5Y", title: "A Day in the Life of a Restaurant Manager | Indeed", channel: "Indeed" },
  ],
  "hr-people": [
    { id: "otVy1P86yaY", title: "A Day in the Life - HR Manager", channel: "Unilever Graduate Careers UK & Ireland" },
    { id: "rp0FlHy0360", title: "A Day in The Life of a Human Resources Professional", channel: "Indeed" },
    { id: "oFMY8fTHGx8", title: "HR Recruitment Administrator - Work life in London", channel: "GetBusyWithMe" },
    { id: "_5YVmtj_Je4", title: "A Day in the Life of a Human Resources Business Partner (HRBP)", channel: "Sanja Williams" },
  ],
  "interior-designer": [
    { id: "Hv17dyreNvc", title: "A day in the life of an interior designer at Morgan Lovell London", channel: "Morgan Lovell | Office Interior Design Specialist" },
    { id: "vcJLa01WFVc", title: "Life as an Interior Designer Based in Ldn.", channel: "jordan anais" },
    { id: "phIGksxA3AY", title: "DESIGN STUDIO LIFE: what interior designers do during the week?", channel: "Space for Edit" },
    { id: "IhRszZfTouI", title: "Day in my life as an interior designer in London", channel: "Mia Tsujimura | The Portfolio Archive " },
  ],
  "investment-analyst": [
    { id: "WZRXceZW_wM", title: "Day in life of a Financial Analyst | What I Do [London, UK]", channel: "The Subtle Investor" },
    { id: "RiHzExK88II", title: "Day in the life of an Investment Banker in London", channel: "Haaris Zamir, CFA" },
    { id: "Izo0jONlIXA", title: "A Day in the Life  - Financial Adviser in London (what really happens)", channel: "Principles Personal Finance" },
    { id: "Aop1fJXplG8", title: "A Day in the Life of an Investment Banker (Analyst to Managing Director)", channel: "Afzal Hussein" },
  ],
  "it-technology": [
    { id: "Ser708FuQiw", title: "A Realistic Day in the Life Working in IT", channel: "Jake's Tech" },
    { id: "VlzvOf0f3rk", title: "24 Hours in the Life of an IT Tech | What To Expect", channel: "The Consistency Lab" },
    { id: "N2XK-XnLnWs", title: "A Day in the Life of IT Helpdesk Support", channel: "Vincent Humble" },
    
  ],
  "jockey": [
    { id: "_bmbbjn40BI", title: "ð¬ð§ A day in the life of dual Champion jockey William Buick", channel: "Godolphin" },
    { id: "5RAxMEfku9Q", title: "A day in the life of Britain's busiest jockey", channel: "Racing Post" },
    { id: "yb2cGYi9fvo", title: "A day in the life of a champion jockey ð| Richard Johnson", channel: "Sky Sports" },
    { id: "et_hLJaH9uM", title: "LIFE AS AN APPRENTICE JOCKEY: HORSE RACING HOW TO", channel: "World Horse Racing" },
  ],
  "kit-manager": [
    { id: "_NTAWHxATX4", title: "I Tried Footballâs TOUGHEST Job", channel: "AwayDays" },
    { id: "eXFw3jWew3k", title: "AMMIES: ALL ACCESS | \\", channel: "Salford City FC" },
    { id: "5UJkDslZzGM", title: "TEAM BEHIND THE TEAM: THE KITMEN EDITION", channel: "Nottingham Forest FC " },
    { id: "j8Qd4YYfbi8", title: "A Day in the Life | Kit Man Olly", channel: "Official Tranmere Rovers" },
  ],
  "legal-compliance": [
    { id: "4IF6xMx7aXQ", title: "HOW TO GET INTO COMPLIANCE | WHAT IS A CAREER IN COMPLIANCE LIKE? | COMPLIANCE ANALYST TELLS ALL!", channel: "Carew Culture" },
    { id: "WXTJ1xPrM6Y", title: "Day in the Life - Legal Operations Senior Manager, Laura  |  FanDuel UK", channel: "FanDuel UK" },
    { id: "xqCKZ_fPHjI", title: "Work Day In My Life | Compliance Analyst (Detailed)", channel: "BeautyandtheKinks" },
    { id: "53b7vvzEL5w", title: "A Week in My Life as a Corporate Lawyer in London (Â£150k+ salary)", channel: "Liam Porritt" },
  ],
  "lettings-negotiator": [
    { id: "SrGz4NbPgto", title: "Day In The Life Of An 18 Year Old Real Estate Agent | London UK", channel: "Bart Chmielecki" },
    { id: "lsnACY-EqCM", title: "A day in the life of our estate agents in the Bedford office", channel: "Michael Graham Living" },
    { id: "FrCT3sGSLD8", title: "Lettings Negotiator Viewing Live Training", channel: "PIP Recruitment" },
    { id: "rkB7Ruq_7Xk", title: "What is the role of a Sales Negotiator. By James Pendleton Estate Agents", channel: "James Pendleton" },
  ],
  "live-events-manager": [
    { id: "AzQ3Xso7sLA", title: "A Day in the Life of a Project Manager | Indeed", channel: "Indeed" },
    { id: "MY8AB1wYOtg", title: "The Absurd Logistics of Concert Tours", channel: "Wendover Productions" },
    { id: "6v18uaoyeHw", title: "What it takes to become an event planner", channel: "Elevate Experiences" },
    { id: "Q0kI3LNChis", title: "What makes a great tour guide and host? | Rick Steves | TEDxSeattleSalon", channel: "TEDx Talks" },
  ],
  "marketing": [
    { id: "e4fmqrVv0mQ", title: "Day in the life as a Digital Marketer | 9-5 office job in London", channel: "Johanna Helena" },
    { id: "0uaPaA0yvXc", title: "A week in the life of a Senior Marketing Executive in UK summer ð¤", channel: "Eleanor Marie Rose" },
    { id: "EfuDipZU6BM", title: "wfh vlog | day in the life of a marketing manager | london diaries", channel: "Monica Guan" },
    { id: "DPPufSnONnE", title: "Day In The LifeâMarketing Manager | 9 to 5 work day", channel: "Heather Feliz" },
  ],
  "mechanic": [
    { id: "3R9WDY6E5P0", title: "A day in the life of a mobile mechanic EP1 | VW wheel bearing | Reno Diag | XC60 alternator", channel: "Kerby" },
    { id: "nut1SVbIP30", title: "Day in the life of an RAC Mobile Mechanic", channel: "RAC" },
    { id: "ZJjCSxhSyz4", title: "Day in the Life of a Mechanic Apprentice | Samâs Light Vehicle Apprenticeship Story", channel: "Golden West Apprenticeships" },
    { id: "815oNGH2mIY", title: "A Day in the Life of a Motorcycle Mechanic â The Reality", channel: "Superbike Surgery Ltd" },
  ],
  "midwife": [
    { id: "RmScHMXKrzw", title: "Day in the Life of a Midwife", channel: "Ochsner Health" },
    { id: "-6D4qerdHrY", title: "Whatâs It Like To Be A Midwife? | One Born Every Minute", channel: "One Born Every Minute" },
    { id: "HBmYbiZ_oho", title: "DAYINTHELIFE  of a  Community Midwife", channel: "County Durham & Darlington NHS Foundation Trust" },
    { id: "EEMOeOUU7zc", title: "A Day in the Life with NHS Community Midwife Amelia", channel: "My World of Work" },
  ],
  "mortgage-advisor": [
    { id: "6G4tAHcOZU4", title: "A Day in the Life of a Trainee Mortgage Broker", channel: "The Mortgage Broker Coach" },
    { id: "3p1ki-uw2_I", title: "What is a Typical Day Like for a Mortgage Broker", channel: "The Mortgage Broker Coach" },
    { id: "7WdgtEIlD6g", title: "Is Being a UK mortgage broker / advisor a good job ? What can I earn ? Is it enjoyable", channel: "Sharon - Starting Afresh at 50!!" },
    { id: "OLuyln2GKJg", title: "What are the day-to-day responsibilities of a Mortgage Advisor?", channel: "Talk FS" },
  ],
  "mortgage-broker": [
    { id: "6G4tAHcOZU4", title: "A Day in the Life of a Trainee Mortgage Broker", channel: "The Mortgage Broker Coach" },
    { id: "3p1ki-uw2_I", title: "What is a Typical Day Like for a Mortgage Broker", channel: "The Mortgage Broker Coach" },
    { id: "7WdgtEIlD6g", title: "Is Being a UK mortgage broker / advisor a good job ? What can I earn ? Is it enjoyable", channel: "Sharon - Starting Afresh at 50!!" },
    { id: "i023-ZoxtpI", title: "How Much Do Mortgage Brokers Earn in the UK", channel: "The Mortgage Broker Coach" },
  ],
  "nurse": [
    { id: "0zM7dOpKTIo", title: "NHS Frontline: A day in the life of a UK nurse | 5 News", channel: "5 News" },
    { id: "AmxE7d5reMA", title: "A day in the life of an Ashgate Hospice Inpatient Unit Nurse", channel: "Ashgate Hospice" },
    { id: "CfVmGIojfX4", title: "A Day in a life of a GP Nurse UK | NHS Nurse", channel: "Claire Carmichael" },
    { id: "AppjgHXc5mo", title: "This Trainee Nurse Has To Work 12-Hour Shifts | Student Nurses E2 | Our Stories", channel: "Our Stories" },
  ],
  "occupational-therapist": [
    { id: "bCd93mutRBo", title: "Occupational Therapist: Day in the life", channel: "Royal Berkshire NHS Foundation Trust" },
    { id: "p3QoTlKhFxs", title: "Life as an occupational therapist", channel: "NHS Health Careers" },
    { id: "KVeTKw3aiMc", title: "A day in the life of an occupational therapist", channel: "Calderdale and Huddersfield NHS Foundation Trust" },
    { id: "tTUBAotQ5F0", title: "Occupational Therapy - 'A day in the life on Placement'", channel: "Oxford Brookes Health & Life Sciences" },
  ],
  "operations": [
    { id: "2t7vKJ_LJRE", title: "A Day In The Life of Tony, an Operations Manager at Amazon UK", channel: "amazonuk" },
    { id: "W_oErtmbSDU", title: "What do Operations Managers Do? Career decisions for an ops job", channel: "Laurence Gartside" },
    { id: "Knlqrbl7dYs", title: "A Day In The Life Of A Logistics Project Manager", channel: "Youth Employment UK" },
    { id: "xwUBzdZMjik", title: "A Day in the Life of a COO", channel: "Yelp for Business" },
  ],
  "performance-engineer": [
    { id: "5zr9MqUewlU", title: "My Job in F1: Emma | Aero Performance Engineer", channel: "Mercedes-AMG Petronas Formula One Team" },
    { id: "hlXE8A08u-Q", title: "Behind The Scenes: A Day In The Life Of A Touring Sound Engineer At An Arena Show", channel: "Rattlin' Bones Club" },
    { id: "yQmHhtAIw_g", title: "My Job in F1: Ola | Aerodynamics", channel: "Mercedes-AMG Petronas Formula One Team" },
    { id: "wUnEDnAYTpE", title: "Day in the Life Training with Olympians (as a Software Engineer)", channel: "Marcos Rico Peng" },
  ],
  "personal-trainer": [
    { id: "ZU3bO5HE5lQ", title: "A Day In A Life Of A Personal Trainer", channel: "Brendan Pearson" },
    { id: "Lc2Av1X2O3c", title: "If I Were A PT and Starting Over, This Is How I'd Make $100k A Year", channel: "James Smith " },
    { id: "9L0dkGscgSs", title: "Is being a Personal Trainer worth it?", channel: "The LODGE Podcast Studio" },
    { id: "LUMqUWDoPbc", title: "Should you become a personal trainer in 2026?", channel: "Tom Grindrod" },
  ],
  "physiotherapist": [
    { id: "RnHsG2UV4uU", title: "A Day in the Life of a Physiotherapist UK", channel: "Days of Dan" },
    { id: "s1jm_V9W3XY", title: "A Day in the Life of a Physical Therapist | Indeed", channel: "Indeed" },
    { id: "RkaCXTnvC7A", title: "Day in The Life as a Physiotherapist", channel: "Shayaan" },
    { id: "XYY3z-VGLYk", title: "A day in the life of a physiotherapist", channel: "LSC Health + Care Partnership" },
  ],
  "plasterer": [
    { id: "sB8nEdREk8o", title: "Passing On 25yrs of Plastering Experience in 30min", channel: "On The Trowel" },
  ],
  "plumber": [
    { id: "P2RpK3Jv4jU", title: "Should You Become A Plumber In 2024 - Apprentice Edition - Day In The Life Apprentice Plumber", channel: "Celsius Heating and Plumbing (Edinburgh)" },
    { id: "-65RSZSigrk", title: "Day in the life of a plumber! Fixing leaks!", channel: "mmplumber" },
  ],
  "producer": [
    { id: "ENb164Blk7E", title: "A Day In The Life Of A Music Producer REALISTIC", channel: "Elliott In The Studio" },
    { id: "BNhEVgfUHxE", title: "Day In The Life Of A Music Producer", channel: "Servida Music" },
    { id: "0RUCNnFJl6k", title: "Day In The Life of a Grammy Nominated Producer", channel: "KXVI" },
    { id: "loUi36bIZ8A", title: "DAY IN THE LIFE OF A MUSIC PRODUCER", channel: "Ocean" },
  ],
  "product": [
    { id: "DMGVK5YLK08", title: "Day in My Life as a Product Designer in London, UK | In-office Edition", channel: "ElenaInProduct" },
    { id: "51B697Z2Xfg", title: "Days in the Life as a Product Designer in London - What it ACTUALLY is like", channel: "amaanioluwa" },
    { id: "MH5nSFq2SKc", title: "Day in the life in a BizOps role (w/ Rob Reiling)", channel: "rocketblocks" },
    { id: "Dnh0jP-GA0o", title: "What I *actually* do as a Product Manager (in 2023)", channel: "Chloe Shih" },
  ],
  "project-management": [
    { id: "AzQ3Xso7sLA", title: "A Day in the Life of a Project Manager | Indeed", channel: "Indeed" },
    { id: "3WDnkBSIm4o", title: "Project Management and Programme Management | What is programme management?", channel: "Association for Project Management" },
    { id: "u-EFQH14GHk", title: "The BEST PROJECT MANAGEMENT INDUSTRIES for Newbies (EXPLAINED)", channel: "Pitol In Motion" },
    { id: "i5v6BRuxB5o", title: "A Day in the Life of a Construction Project Manager | Indeed", channel: "Indeed" },
  ],
  "property-manager": [
    { id: "_Hy2z4zbZlQ", title: "A Day in the Life of a Property Manager at GoldenWest Management", channel: "GoldenWest Management, Inc" },
    { id: "d7nPO70VPNQ", title: "A Day In The Life Of A Property Manager: An Inside Look At Managing Properties", channel: "DoorLoop" },
    { id: "kzYZVZNdSFM", title: "5 IMPORTANT Duties of a Property Manager EXPLAINED", channel: "Property Hustlers " },
    { id: "0LQULZ4ir3s", title: "Day in the life of a Property Manager in TN!! Overseeing a Multi-Million dollar facility!", channel: "Day Dean" },
  ],
  "psychotherapist": [
    { id: "bCd93mutRBo", title: "Occupational Therapist: Day in the life", channel: "Royal Berkshire NHS Foundation Trust" },
    { id: "KVeTKw3aiMc", title: "A day in the life of an occupational therapist", channel: "Calderdale and Huddersfield NHS Foundation Trust" },
    { id: "c7COPYKl6cg", title: "Hannah Elliott - Art Therapy Student", channel: "NHS England Workforce, Training and Education" },
    { id: "3ganVrw0rac", title: "A Day in My Life as a Psychotherapist Private Practice | Mental Health Therapist | Counsellor", channel: "John-Paul Davies" },
  ],
  "qa-tester": [
    { id: "HdcS2nWTsjc", title: "Day in the Life of a Test Automation Engineer in London ð¬ð§ð©âð»â¨ððââï¸ð¥| Mini Vlogâ¨", channel: "Gc In England" },
    { id: "ChhYCujkMZ0", title: "A Day In The Life of a QA Tester at a Software Development Company", channel: "Silverchip Ltd" },
    { id: "0eMBOjS9tvY", title: "NO EXPERIENCE - How to Get a Job in Software Testing and QA, 2025", channel: "Evgeny Kim" },
    { id: "lhJ6bAOdce8", title: "2026 Software Testing Job Market - QA Engineer AI", channel: "Codemify" },
  ],
  "race-engineer": [
    { id: "5zr9MqUewlU", title: "My Job in F1: Emma | Aero Performance Engineer", channel: "Mercedes-AMG Petronas Formula One Team" },
    { id: "fhc7UhSuorA", title: "How to Get a Job in Formula 1 -  Tips from Red Bull Engineer (2022)", channel: "BrrrakeF1" },
    { id: "Vd5CX2C1Iaw", title: "Formula 1 Engineering Tour - Trackside", channel: "Visa Cash App RB F1 Team" },
    { id: "q7KsPnCd-mE", title: "How to Get a Job in Motorsport", channel: "Driver61" },
  ],
  "racehorse-trainer": [
    { id: "Y6lCY50xJ0o", title: "A Day In The Life: Harry Eustace, the racehorse trainer with a perfect record at Royal Ascot", channel: "oddschecker" },
    { id: "QCYWBRZeBp0", title: "A Winner At Newbury! A Day in the Life of Horse Racing Trainer Harry Derham On Race Day | OLBG", channel: "OLBG" },
    { id: "ZXw0JI8rPF4", title: "A day in the life of a work rider | National Racehorse Week", channel: "Great British Racing" },
    { id: "RGJqmsc0NB0", title: "Day in the Life of a Thoroughbred Trainer with TVGâs Nick Hines: Segment 1 of 5", channel: "FanDuel Racing" },
  ],
  "repair-technician": [
    { id: "qhFVD0J_sRA", title: "A day in the life of a Pacifica engineer", channel: "Pacifica Group Ltd" },
  ],
  "reporter": [
    { id: "XfzGKRIBTuk", title: "BEHIND THE SCENES | A Day In The Life Of A Liverpool Reporter", channel: "David Lynch - Liverpool FC" },
    { id: "5uN9sF-z0z0", title: "I Wanna Be a Journalist Â· A Day In The Life Of A Journalist", channel: "Student Edge" },
    { id: "oMFNw9MHcxE", title: "Being a Woman in Investigative Journalism | Trafficked | National Geographic UK", channel: "National Geographic UK" },
    { id: "Gpq6lPtDUMg", title: "A Day in the Life of a Reporter", channel: "Matt Mead" },
  ],
  "retail-assistant": [
    { id: "h92TcOfsggM", title: "A Day in the Life of a Retail Sales Associate ð | Indeed", channel: "Indeed" },
    { id: "vM7rsb28JYY", title: "A Day in the Life of Next Retail", channel: "Life at Next" },
    { id: "HgJPtRzLF_0", title: "A day in the life of a UNIQLO Sales Assistant", channel: "UNIQLO Europe" },
    { id: "QA1CXYasVFc", title: "A day in the life of a Retail Operations Assistant", channel: "Boots Jobs" },
  ],
  "roofer": [
    { id: "rjisMybq-iw", title: "Roofer - Career Insights (Careers in Construction)", channel: "Career Insights" },
  ],
  "sales": [
    { id: "DiJQON4efuA", title: "A Day in the Life | Petr, Clinical Sales Representative", channel: "Boston Scientific EMEA" },
    { id: "4-VXr0OHDQg", title: "Day in the Life of my Remote Tech Sales Job (Work From Home)", channel: "SaaS & The City" },
    { id: "VNtJgjOLHSE", title: "A Day In The Life Of A Medical Sales Rep...", channel: "Med Sales With Matt" },
    { id: "-eSMf21pFl0", title: "Morgan Stanley Sales & Trading VP - A Day in the Life", channel: "Mark Ross" },
  ],
  "sound-engineer": [
    { id: "Nc-uyEbBrZQ", title: "A Day in the Life of a Sound Engineer", channel: "WorkingNation Educates" },
    { id: "DKXLXyRDzIQ", title: "A Day In The Life of An Audio Engineer", channel: "Alex Markides" },
    { id: "XZSl6ut-068", title: "How I Make $5k A Month As A Live Sound Engineer", channel: "Offshore Audio" },
    { id: "hlXE8A08u-Q", title: "Behind The Scenes: A Day In The Life Of A Touring Sound Engineer At An Arena Show", channel: "Rattlin' Bones Club" },
  ],
  "sports-scientist": [
    { id: "j-mbyJR4OLg", title: "So you want to be a Sport Scientist", channel: "Sika Strength" },
    { id: "pofkS7rBTP8", title: "BEHIND BLUE EYES EP.5 | Everton's Sports Science Department", channel: "Everton Football Club" },
    { id: "irzpcHHqrNk", title: "Sports science intern Faye Stockwell on her role at Rovers", channel: "Doncaster Rovers" },
    { id: "gHcCsGvDRWA", title: "BECOMING A SPORT SCIENTIST: My Journey, Vision for the Channel & More!", channel: "NJ Sport Science - Nick Jankovskis" },
  ],
  "stable-hand": [
    { id: "F5QUc6mbF5A", title: "A DAY IN THE LIFE OF AN EQUESTRIAN GROOM!!", channel: "Sarah Rogers" },
    { id: "QHPsqg6ox8E", title: "Day in the life of a Stable Hand", channel: "CareersBox" },
    { id: "KvATat0fNSI", title: "A day in the life of an Equine Racing Apprentice!", channel: "Haddon Training Ltd" },
    { id: "Utd5EEWTKFE", title: "I Was An Apprentice For The Day - Horse Stable hand", channel: "Tom's Roundabout Crew" },
  ],
  "strategy": [
    { id: "IN4CpdIDv08", title: "A Day in the Life of a Strategy Consultant in London", channel: "Elizabeth Filips" },
    { id: "c6fs1gBpjQg", title: "A Day in the Life of a Management Consultant", channel: "Jason Lai" },
    { id: "9GumiLIxLMM", title: "How Millionaire Bankers Actually Work | Authorized Account | Insider", channel: "Insider" },
    
  ],
  "sustainability": [
    { id: "NFzqvsVH7D0", title: "Your Guide to Becoming a Sustainability Manager | Career Roadmap No. 5", channel: "Maddy Albee" },
  ],
  "stylist": [
    { id: "e-HZ2TIVULI", title: "A Day in the Life of Fashion Designer Thom Browne | Vogue", channel: "Vogue" },
    { id: "ohexJG7_tXk", title: "A Day in the Life of a Stylist in Paris | Jordan Boothe", channel: "Jordan Boothe" },
    { id: "ub0Ei0lOr-w", title: "A Day In the Life of Natalie Joos, Stylist & Blogger", channel: "New York Magazine" },
    { id: "bK_fnLCgF9M", title: "How to Become a Creative Director with Alexa Chung | Future of Fashion | British Vogue", channel: "Vogue" },
  ],
  "teacher": [
    { id: "xVFECZnmK2w", title: "A Day in the Life of a Primary School Teacher | A Day in the Life of a Primary ECT ð", channel: "Cher's Cool Beans" },
    { id: "Piw-9dOC8YQ", title: "A Day in the Life of a Primary School Teacher", channel: "universityworcester" },
    { id: "qcDZQdHHzZE", title: "A DAY IN THE LIFE OF A YEAR 3 TEACHER || PRIMARY SCHOOL TEACHER || VLOG", channel: "Gifty Kwaofio" },
    { id: "De_oQ7UqXqw", title: "TEACHER VLOG: full day in my life & finding work-life balance!", channel: "lindseyteaches" },
  ],
  "teaching-assistant": [
    { id: "3otvlNnJrtM", title: "Is Being a Teaching Assistant in the UK Worth It?", channel: "Udochi Adachuks" },
    { id: "Z-d_9JIpJuY", title: "A day in the life of a teaching assistant at Woodlands School.", channel: "Woodlands Special School Harrow" },
    { id: "UDFCbMBGPYA", title: "Day in the life of a Teaching Assistant", channel: "NEAutismSociety" },
    { id: "jVtCMISuivQ", title: "Tips for being a successful teaching assistant / my last day as a TA", channel: "vids by j" },
  ],
  "theatre-producer": [
    { id: "2cksCqCUwLo", title: "Careers in Theatre Producing - Insider Panel I TheatreCraft 2021", channel: "OfficialLondonTheatre" },
    { id: "lDFOQHh6VFs", title: "Becky Barber explains the role of a theatre producer", channel: "Becky Barber Producing Masterclass" },
  ],
  "travel-consultant": [
    { id: "SE1Kvis0lnA", title: "10 Things I Wish I Knew BEFORE I Became a Travel Agent (Plus, What Others Won't Tell You)", channel: "Travel Agent Haven" },
    { id: "HDuW1-_S1Uk", title: "A day in the life of a Corporate Travel Consultant - UK", channel: "Flight Centre Travel Group Careers" },
    { id: "D1yDKaE16fI", title: "London Vlog: A Day in the Life of a Travel Agent - Taste Film Experience", channel: "Nonstop_Jen" },
    { id: "CySaf9g8CVI", title: "A Day in Sueâs Life as a Travel Consultant", channel: "American Express Global Business Travel" },
  ],
  "vehicle-technician": [
    { id: "nut1SVbIP30", title: "Day in the life of an RAC Mobile Mechanic", channel: "RAC" },
    { id: "78-U3rEe7LM", title: "A day in the life of a UK Auto Electrician,14-Hour Day | Life Inside a Car Diagnostics Shop", channel: "RMS DIAGNOSTICS" },
    { id: "vDZXXQH3qqw", title: "Avoiding Disaster: A Day in the Life of a UK HGV Mechanic in Wales", channel: "ONT TOOLS" },
    { id: "7NYaYBn9c3c", title: "From Apprentice to HGV Technician... Meet Matthew Collins!", channel: "VolvoTrucksUK" },
  ],
  "veterinary-nurse": [
    { id: "81RglnJff-s", title: "A Day in the Life of a Veterinary Nurse", channel: "msuvets" },
    { id: "e2bTfk4D6Nk", title: "WE ARE VETERINARY NURSES", channel: "Davies Veterinary Specialists" },
    { id: "l-E59LT7JQw", title: "Day in the life of a veterinary nurse", channel: "StGeorges Vet" },
    { id: "spXekWQXALE", title: "Veterinary nurses - true professionals", channel: "Royal College of Veterinary Surgeons (RCVS)" },
  ],
  "veterinary-surgeon": [
    { id: "pm0l6Piqxt0", title: "A DAY N THE LIFE OF A VET: A Vulnerable Vlog", channel: "Dr Bolu Eso" },
    { id: "YKqKTopeRaU", title: "Day in the life of a veterinarian from 8am to 8pm (realistic & unglamorous)", channel: "May Yean" },
    { id: "nMRA4-BVebs", title: "A Day in the Life of a Veterinarian | Indeed", channel: "Indeed" },
    { id: "sXEBno3xJjE", title: "Notes from the ER: Inside a Veterinary Emergency Room", channel: "The Schwarzman Animal Medical Center" },
  ],
  "warehouse-delivery": [
    { id: "SkGjjX-y-JI", title: "Life as a Home Delivery Driver at Milk & More", channel: "Milk & More" },
    { id: "5BQ0AcVu40A", title: "24 Hours inside a NEXT Warehouse", channel: "Life at Next" },
    { id: "jzg4snTtk3E", title: "DAY IN THE LIFE Working at an AMAZON Warehouse (INSIDE FOOTAGE)", channel: "Mayaamc" },
    { id: "OgUtNKN3jbU", title: "Behind The Scenes Of DHL Delivery [4K] | Logistics of the Future | Spark", channel: "Spark" },
  ],
  "wealth-manager": [
    { id: "Izo0jONlIXA", title: "A Day in the Life  - Financial Adviser in London (what really happens)", channel: "Principles Personal Finance" },
    { id: "jLpN8ay3Fow", title: "Day in the Life of a Private Client Advisor | Wealth Management | J.P. Morgan", channel: "jpmorgan" },
    { id: "UIA-K2uVCqY", title: "Finance Jobs with GREAT Work Life Balance & HIGH Pay", channel: "Shawn Hakimi" },
    { id: "4I8Um21du78", title: "Day in the Life of a Wealth Management Analyst | JPMorgan Chase & Co.", channel: "jpmorgan" },
  ],
  "football-agent": [
    { id: "AoZ0WO0-yU4", title: "Do Players Actually Need Agents?", channel: "Athletic Interest" },
    { id: "WzFTP7Sj5FA", title: "How to Become a FIFA Agent (What Nobody Tells You First)", channel: "Brian Football Insider" },
    { id: "lyZcN40C_jk", title: "How I Passed the FIFA Agent Exam: Insights and Tips to Reach 81% Pass Rate", channel: "Samuele Mura" },
    { id: "wtWGA0hChiY", title: "Being a Football Agent: Getting into the Business (7 real tips)", channel: "Samuele Mura" },
  ],
  "isrc-manager": [
    { id: "ZeorINQB2RA", title: "DO THIS Before Your Next Release! (ISRC CODES)", channel: "Spinlight Studio" },
    { id: "214RpprAltU", title: "What is ISRC code? (ISRC Number)", channel: "The Modern Musician" },
    { id: "NP974uzvRGw", title: "ISRC Codes - What Are They? | Do You Need One?", channel: "Charles Cleyn" },
    { id: "n-AupJuMlCU", title: "What is an ISRC code and why do you need one?", channel: "Abbey Road" },
  ],
  "literary-agent": [
    { id: "uCsZmeydAiI", title: "Come to Work With Me... Literary Agent Edition!", channel: "Publishers Association" },
    { id: "DHvt7qUCX2E", title: "Day in the Life of a Literary Agent | Literary Agent Stephanie Fretwell Hill", channel: "Middle Grade Ninja" },
  ],
  "bookseller": [
    { id: "2jotS_0evWM", title: "A day in the life of... a Waterstones bookseller!", channel: "Publishers Association" },
  ],
};
